apiVersion: v1
kind: Pod
metadata: 
  name: persistent-pod1
spec: 
  containers:
    - name: persistent-pod1
      image: nginx
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: persistent-pod-storage
  volumes:
    - name: persistent-pod-storage
      persistentVolumeClaim:
        claimName: demo-pvc
